general:
  label: 基础设置
  items:
    index_slogn:
      name: index_slogn
      label: 首页描述
      type: text

    tags_slogn:
      name: tags_slogn
      label: 标签页描述
      type: text

    archives_slogn:
      name: archives_slogn
      label: 归档页描述
      type: text

    search_slogn:
      name: search_slogn
      label: 搜索页描述
      type: text

    index_cover:
      name: index_cover
      label: 首页顶部图
      type: attachment

    tags_cover:
      name: tags_cover
      label: 标签页顶部图
      type: attachment

    archives_cover:
      name: archives_cover
      label: 归档页顶部图
      type: attachment

    search_cover:
      name: search_cover
      label: 搜索页页顶部图
      type: attachment

    notice:
      name: notice
      label: 公告
      type: textarea

sns:
  label: 社交设置
  items:
    rss:
      name: rss
      label: RSS
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭

    weibo:
      name: weibo
      label: 微博
      type: text

    zhihu:
      name: zhihu
      label: 知乎
      type: text

    github:
      name: github
      label: Github
      type: text

    twitter:
      name: twitter
      label: Twitter
      type: text

    bilibili:
      name: bilibili
      label: BiliBili
      type: text

    steam:
      name: steam
      label: Steam
      type: text

    mail:
      name: mail
      label: 邮箱
      type: text

style:
  label: 样式设置
  items:
    sidebar:
      name: sidebar
      label: 侧边栏
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 显示
        - value: false
          label: 隐藏
    sidebar_tags:
      name: sidebar_tags
      label: 侧边栏标签
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 显示
        - value: false
          label: 隐藏
    sidebar_links:
      name: sidebar_links
      label: 侧边栏友链
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 显示
        - value: false
          label: 隐藏
    code_pretty:
      name: code_pretty
      label: 文章代码高亮主题
      type: select
      default: Default
      options:
        - value: ''
          label: '无'
        - value: '-coy'
          label: 'Coy'
        - value: '-dark'
          label: 'Dark'
        - value: '-funky'
          label: 'Funky'
        - value: '-okaidia'
          label: 'Okaidia'
        - value: '-solarizedlight'
          label: 'Solarized Light'
        - value: '-tomorrow'
          label: 'Tomorrow'
        - value: '-twilight'
          label: 'Twilight'
